/* ==========================================================================
   Josh Serpis — playground pens
   Every pen is one object. To add one, copy the block and change the fields:

     slug   unique, url-safe — used for #deep-links
     title  shown on the card and in the editor bar
     blurb  one line, what it does
     tags   lowercase, hyphenated; they drive the filter row
     html   markup for the frame's <body>
     css    styles; the palette tokens (--amber, --indigo, --surface...) are
            already injected, so pens can use them directly
     js     runs after the markup, inside a sandboxed frame

   Written as template literals, so avoid backticks inside pen source.
   ========================================================================== */
window.PENS = [

  /* ---------------------------------------------------------------- */
  {
    slug: "orbit-field",
    title: "Orbit field",
    blurb: "The site's signature planets. Each one rides an SVG motion path with offset-rotate turned off, so it travels the ellipse without ever tipping over.",
    tags: ["css", "motion"],
    html: [
      '<div class="sky">',
      '  <svg class="rings" viewBox="0 0 440 440" aria-hidden="true">',
      '    <ellipse cx="220" cy="220" rx="70"  ry="30"/>',
      '    <ellipse cx="220" cy="220" rx="110" ry="47"/>',
      '    <ellipse cx="220" cy="220" rx="155" ry="66"/>',
      '    <ellipse cx="220" cy="220" rx="200" ry="85"/>',
      '  </svg>',
      '',
      '  <span class="sun"></span>',
      '',
      '  <i class="planet p1"></i>',
      '  <i class="planet p2"></i>',
      '  <i class="planet p3"></i>',
      '  <i class="planet p4"></i>',
      '</div>'
    ].join("\n"),
    css: [
      "body { display: grid; place-items: center; min-height: 100vh; overflow: hidden; }",
      "",
      "/* fixed 440px stage: offset-path takes real pixels, so the rings and",
      "   the paths below have to share one coordinate space */",
      ".sky { position: relative; width: 440px; height: 440px; }",
      "",
      ".rings { position: absolute; inset: 0; width: 100%; height: 100%; }",
      ".rings ellipse { fill: none; stroke: rgba(249, 249, 255, 0.14); stroke-width: 1; }",
      "",
      ".sun {",
      "  position: absolute;",
      "  top: 50%; left: 50%;",
      "  width: 26px; height: 26px;",
      "  margin: -13px 0 0 -13px;",
      "  border-radius: 50%;",
      "  background: var(--amber);",
      "  box-shadow: 0 0 44px 8px rgba(255, 195, 41, 0.3);",
      "}",
      "",
      ".planet {",
      "  position: absolute;",
      "  top: 0; left: 0;",
      "  width: var(--s); height: var(--s);",
      "  border-radius: 50%;",
      "  background: var(--c);",
      "  /* the planet centres itself on the path and refuses to turn with it */",
      "  offset-rotate: 0deg;",
      "  animation: ride var(--t) linear infinite;",
      "}",
      "",
      "/* each path is the same ellipse as its ring, written as two arcs */",
      ".p1 { --s: 13px; --c: var(--amber);       --t: 9s;",
      "      offset-path: path('M 150,220 a 70,30 0 1,0 140,0 a 70,30 0 1,0 -140,0'); }",
      ".p2 { --s: 21px; --c: var(--indigo-lift); --t: 15s;",
      "      offset-path: path('M 110,220 a 110,47 0 1,0 220,0 a 110,47 0 1,0 -220,0'); }",
      ".p3 { --s: 10px; --c: var(--amethyst);    --t: 24s;",
      "      offset-path: path('M 65,220 a 155,66 0 1,0 310,0 a 155,66 0 1,0 -310,0'); }",
      ".p4 { --s: 28px; --c: var(--amber-deep);  --t: 34s;",
      "      offset-path: path('M 20,220 a 200,85 0 1,0 400,0 a 200,85 0 1,0 -400,0'); }",
      "",
      "@keyframes ride { to { offset-distance: 100%; } }",
      "",
      "/* the stage is a fixed size, so shrink the whole thing on small frames */",
      "@media (max-width: 480px) { .sky { transform: scale(0.72); } }",
      "",
      "@media (prefers-reduced-motion: reduce) { .planet { animation: none; } }"
    ].join("\n"),
    js: ""
  },

  /* ---------------------------------------------------------------- */
  {
    slug: "token-stream",
    title: "Token stream",
    blurb: "What streaming actually looks like: chunks arriving at uneven intervals, a caret that never quite settles, and a live tokens-per-second read-out.",
    tags: ["ai", "javascript"],
    html: [
      '<div class="panel">',
      '  <p class="prompt"><b>&gt;</b> Explain retrieval-augmented generation in one paragraph.</p>',
      '  <p class="out" id="out"><span class="caret"></span></p>',
      '  <div class="bar">',
      '    <span id="stat">idle</span>',
      '    <button id="go" type="button">Stream</button>',
      '  </div>',
      '</div>'
    ].join("\n"),
    css: [
      "body { display: grid; place-items: center; min-height: 100vh; padding: 22px; }",
      "",
      ".panel {",
      "  width: min(520px, 100%);",
      "  border: 1px solid rgba(255, 255, 255, 0.1);",
      "  border-radius: 16px;",
      "  background: rgba(255, 255, 255, 0.03);",
      "  padding: 22px;",
      "}",
      "",
      ".prompt { font-family: var(--mono); font-size: 12px; color: var(--outline); margin-bottom: 16px; }",
      ".prompt b { color: var(--amber); }",
      "",
      ".out { min-height: 8.5em; line-height: 1.7; font-size: 15px; color: var(--on-surface); }",
      "",
      "/* the caret sits inline and blinks only while idle */",
      ".caret {",
      "  display: inline-block;",
      "  width: 8px; height: 1.05em;",
      "  vertical-align: text-bottom;",
      "  background: var(--amber);",
      "  animation: blink 1s steps(2) infinite;",
      "}",
      ".is-streaming .caret { animation: none; }",
      "@keyframes blink { 50% { opacity: 0; } }",
      "",
      ".bar {",
      "  display: flex; align-items: center; justify-content: space-between;",
      "  gap: 14px; margin-top: 20px; padding-top: 16px;",
      "  border-top: 1px solid rgba(255, 255, 255, 0.1);",
      "  font-family: var(--mono); font-size: 11px;",
      "  letter-spacing: 0.1em; text-transform: uppercase; color: var(--outline);",
      "}",
      "",
      "button {",
      "  font: inherit; letter-spacing: 0.12em; text-transform: uppercase;",
      "  padding: 8px 16px; border-radius: 999px;",
      "  border: 1px solid rgba(255, 195, 41, 0.45);",
      "  background: none; color: var(--amber); cursor: pointer;",
      "  transition: background 0.25s, color 0.25s;",
      "}",
      "button:hover { background: var(--amber); color: var(--surface); }"
    ].join("\n"),
    js: [
      "var ANSWER = 'Retrieval-augmented generation puts a search step in front of the model. ' +",
      "  'Rather than relying on what the weights happen to remember, the system finds the ' +",
      "  'passages most relevant to the question, drops them into the prompt, and asks the ' +",
      "  'model to answer from those. You get citations, cheaper updates, and a much shorter ' +",
      "  'path from a wrong answer to the document that caused it.';",
      "",
      "var out = document.getElementById('out');",
      "var stat = document.getElementById('stat');",
      "var go = document.getElementById('go');",
      "var caret = document.querySelector('.caret');",
      "var timer = null;",
      "",
      "/* split on whitespace but keep it — closer to how tokens actually arrive */",
      "function tokenise(text) {",
      "  var raw = text.split(/(\\s+)/);",
      "  var out = [];",
      "  for (var i = 0; i < raw.length; i++) {",
      "    var piece = raw[i];",
      "    /* long words arrive in two or three pieces, like real sub-word tokens */",
      "    if (piece.length > 7) {",
      "      out.push(piece.slice(0, 4));",
      "      out.push(piece.slice(4));",
      "    } else if (piece.length) {",
      "      out.push(piece);",
      "    }",
      "  }",
      "  return out;",
      "}",
      "",
      "function stream() {",
      "  clearTimeout(timer);",
      "  var tokens = tokenise(ANSWER);",
      "  var i = 0;",
      "  var started = performance.now();",
      "  var text = document.createTextNode('');",
      "",
      "  out.textContent = '';",
      "  out.appendChild(text);",
      "  out.appendChild(caret);",
      "  document.body.classList.add('is-streaming');",
      "  go.textContent = 'Stop';",
      "",
      "  function tick() {",
      "    if (i >= tokens.length) { stop(); return; }",
      "    text.nodeValue += tokens[i];",
      "    i++;",
      "",
      "    var seconds = (performance.now() - started) / 1000;",
      "    stat.textContent = i + ' tokens · ' + (i / seconds).toFixed(1) + ' tok/s';",
      "",
      "    /* uneven gaps, with the occasional stall a real endpoint gives you */",
      "    var wait = 14 + Math.random() * 46;",
      "    if (Math.random() < 0.04) wait += 320;",
      "    timer = setTimeout(tick, wait);",
      "  }",
      "",
      "  tick();",
      "}",
      "",
      "function stop() {",
      "  clearTimeout(timer);",
      "  timer = null;",
      "  document.body.classList.remove('is-streaming');",
      "  go.textContent = 'Replay';",
      "}",
      "",
      "go.addEventListener('click', function () {",
      "  if (timer) { stop(); stat.textContent = 'stopped'; return; }",
      "  stream();",
      "});",
      "",
      "stream();"
    ].join("\n")
  },

  /* ---------------------------------------------------------------- */
  {
    slug: "goo-pointer",
    title: "Goo pointer",
    blurb: "An SVG blur-and-contrast filter turns four lagging circles into one liquid mass. Move the pointer; the trailing blobs decide how far it stretches.",
    tags: ["svg", "motion"],
    html: [
      '<svg class="defs" aria-hidden="true">',
      '  <filter id="goo">',
      '    <feGaussianBlur in="SourceGraphic" stdDeviation="11" result="blur"/>',
      '    <feColorMatrix in="blur" mode="matrix"',
      '      values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 26 -12" result="goo"/>',
      '    <feBlend in="SourceGraphic" in2="goo"/>',
      '  </filter>',
      '</svg>',
      '',
      '<div class="goo">',
      '  <span class="blob" style="--s:66px"></span>',
      '  <span class="blob" style="--s:52px"></span>',
      '  <span class="blob" style="--s:38px"></span>',
      '  <span class="blob" style="--s:24px"></span>',
      '</div>',
      '',
      '<p class="hint">move the pointer</p>'
    ].join("\n"),
    css: [
      "body { min-height: 100vh; overflow: hidden; cursor: crosshair; }",
      "",
      ".defs { position: absolute; width: 0; height: 0; }",
      "",
      "/* the filter merges anything inside this layer */",
      ".goo { position: fixed; inset: 0; filter: url(#goo); }",
      "",
      ".blob {",
      "  position: absolute;",
      "  top: 0; left: 0;",
      "  width: var(--s); height: var(--s);",
      "  margin: calc(var(--s) / -2) 0 0 calc(var(--s) / -2);",
      "  border-radius: 50%;",
      "  background: var(--indigo-lift);",
      "  will-change: transform;",
      "}",
      ".blob:first-child { background: var(--amber); }",
      "",
      ".hint {",
      "  position: fixed;",
      "  left: 50%; bottom: 26px;",
      "  transform: translateX(-50%);",
      "  font-family: var(--mono);",
      "  font-size: 10px;",
      "  letter-spacing: 0.22em;",
      "  text-transform: uppercase;",
      "  color: var(--outline);",
      "}"
    ].join("\n"),
    js: [
      "var blobs = [].slice.call(document.querySelectorAll('.blob'));",
      "var target = { x: innerWidth / 2, y: innerHeight / 2 };",
      "",
      "/* each blob chases the one in front of it, so lag compounds down the chain */",
      "var points = blobs.map(function () { return { x: target.x, y: target.y }; });",
      "",
      "function move(e) {",
      "  var touch = e.touches && e.touches[0];",
      "  target.x = touch ? touch.clientX : e.clientX;",
      "  target.y = touch ? touch.clientY : e.clientY;",
      "}",
      "",
      "addEventListener('pointermove', move, { passive: true });",
      "addEventListener('touchmove', move, { passive: true });",
      "",
      "function loop() {",
      "  var lead = target;",
      "",
      "  for (var i = 0; i < points.length; i++) {",
      "    var p = points[i];",
      "    var ease = 0.26 - i * 0.045;",
      "    p.x += (lead.x - p.x) * ease;",
      "    p.y += (lead.y - p.y) * ease;",
      "    blobs[i].style.transform = 'translate3d(' + p.x.toFixed(1) + 'px,' + p.y.toFixed(1) + 'px,0)';",
      "    lead = p;",
      "  }",
      "",
      "  requestAnimationFrame(loop);",
      "}",
      "",
      "loop();"
    ].join("\n")
  },

  /* ---------------------------------------------------------------- */
  {
    slug: "attention-map",
    title: "Attention map",
    blurb: "A toy attention head on canvas. Scores drift, each row softmaxes to one, and the brightest cell in every row is the token that head is actually looking at.",
    tags: ["ai", "canvas"],
    html: '<canvas id="map"></canvas>',
    css: [
      "body { display: grid; place-items: center; min-height: 100vh; padding: 16px; }",
      "canvas { width: 100%; max-width: 520px; height: auto; display: block; }"
    ].join("\n"),
    js: [
      "var TOKENS = ['the', 'model', 'reads', 'every', 'token', 'at', 'once', 'and'];",
      "var N = TOKENS.length;",
      "var canvas = document.getElementById('map');",
      "var ctx = canvas.getContext('2d');",
      "",
      "var PAD = 74;      /* room for the labels */",
      "var CELL = 46;",
      "var SIZE = PAD + CELL * N + 10;",
      "var dpr = Math.min(2, window.devicePixelRatio || 1);",
      "",
      "canvas.width = SIZE * dpr;",
      "canvas.height = SIZE * dpr;",
      "canvas.style.aspectRatio = '1';",
      "ctx.scale(dpr, dpr);",
      "",
      "/* raw scores: a diagonal bias (tokens attend to themselves) plus drift */",
      "var phase = [];",
      "for (var i = 0; i < N * N; i++) phase.push(Math.random() * Math.PI * 2);",
      "",
      "function scores(t) {",
      "  var rows = [];",
      "  for (var r = 0; r < N; r++) {",
      "    var row = [];",
      "    for (var c = 0; c < N; c++) {",
      "      var near = 1.6 / (1 + Math.abs(r - c) * 0.9);",
      "      var drift = Math.sin(t * 0.0007 + phase[r * N + c]) * 1.1;",
      "      row.push(near + drift);",
      "    }",
      "    rows.push(softmax(row));",
      "  }",
      "  return rows;",
      "}",
      "",
      "function softmax(row) {",
      "  var max = Math.max.apply(null, row);",
      "  var exp = row.map(function (v) { return Math.exp(v - max); });",
      "  var sum = exp.reduce(function (a, b) { return a + b; }, 0);",
      "  return exp.map(function (v) { return v / sum; });",
      "}",
      "",
      "function draw(t) {",
      "  var rows = scores(t);",
      "",
      "  ctx.clearRect(0, 0, SIZE, SIZE);",
      "  ctx.font = '10px ui-monospace, monospace';",
      "  ctx.textBaseline = 'middle';",
      "",
      "  for (var r = 0; r < N; r++) {",
      "    /* the token this row is looking at hardest */",
      "    var peak = rows[r].indexOf(Math.max.apply(null, rows[r]));",
      "",
      "    ctx.fillStyle = '#8f9097';",
      "    ctx.textAlign = 'right';",
      "    ctx.fillText(TOKENS[r], PAD - 12, PAD + r * CELL + CELL / 2);",
      "",
      "    ctx.save();",
      "    ctx.translate(PAD + r * CELL + CELL / 2, PAD - 12);",
      "    ctx.rotate(-Math.PI / 4);",
      "    ctx.textAlign = 'left';",
      "    ctx.fillText(TOKENS[r], 0, 0);",
      "    ctx.restore();",
      "",
      "    for (var c = 0; c < N; c++) {",
      "      var w = rows[r][c];",
      "      var x = PAD + c * CELL;",
      "      var y = PAD + r * CELL;",
      "",
      "      /* indigo ground warming to amber as weight climbs */",
      "      ctx.fillStyle = 'rgba(70, 72, 212,' + (0.12 + w * 1.2) + ')';",
      "      ctx.fillRect(x, y, CELL - 3, CELL - 3);",
      "      ctx.fillStyle = 'rgba(255, 195, 41,' + (w * w * 3.4) + ')';",
      "      ctx.fillRect(x, y, CELL - 3, CELL - 3);",
      "",
      "      if (c === peak) {",
      "        ctx.strokeStyle = 'rgba(255, 195, 41, 0.9)';",
      "        ctx.lineWidth = 1;",
      "        ctx.strokeRect(x + 0.5, y + 0.5, CELL - 4, CELL - 4);",
      "      }",
      "    }",
      "  }",
      "",
      "  requestAnimationFrame(draw);",
      "}",
      "",
      "requestAnimationFrame(draw);"
    ].join("\n")
  }

];
